[package]
name = "doc_fail"
version = "0.1.0"
edition = "2024"

[dependencies]
iroh = "0.91.1"
iroh-blobs = "0.93.0"
iroh-docs = "0.91.0"
iroh-gossip = "0.91.0"
tokio = { version = "1", features = ["sync", "rt", "time", "io-util"] }
anyhow = "1"
n0-future = "0.2.0"
